# NUMPY ASSIGNMENT ( NITISH KUMAR PILLA )

In [12]:
#  Alexandre Theophile Vandermonde

import numpy as np
def vander(ip,n,increasing=False):
    if increasing == False:
        vec=[]
        for x in ip:
            for i in range(n):
                vec.append(x**(n-1-i))
    else:
        vec=[]
        for x in ip:
            for i in range(n):
                vec.append(x**i)
    return np.array(vec).reshape(len(ip),n)

print(vander([1,2,3,4,5],5,increasing=False))
print('\n')
print(vander([2,5,4,77,8,2],3,increasing=True))
        

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


[[   1    2    4]
 [   1    5   25]
 [   1    4   16]
 [   1   77 5929]
 [   1    8   64]
 [   1    2    4]]


In [24]:
#  moving average in an array over a window

def moving_avg(x,k):
    ans=[]
    for i in range(len(x)-k+1):
        ans.append((sum(x[i:k+i])/k))
    return np.array(ans).round(3)

moving_avg([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150],3)

array([  5.   ,   4.667,   5.667,   6.667,   9.667,  28.667,  49.333,
        72.667,  84.   ,  93.333, 116.333])